version: "3.1"
services:
  nginx:
    image: nginx:alpine
    ports:
    - "8080:80"
    volumes:
    - ./static:/srv/www/static
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - nodejs
  nodejs:
    image: node:alpine
    environment:
      NODE_ENV: development
    working_dir: /home/app
    restart: always
    volumes:
    - .:/home/app
    command: ["node", "index"]